In [3]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr.shape)
print(arr.ndim)
print(arr.size)

print(arr[1, :])

(3, 3)
2
9
[40 50 60]


In [4]:
print(arr[:, 2])

print(arr[arr > 45])

[30 60 90]
[50 60 70 80 90]


In [ ]:
print(arr.mean(axis = 1))

print(arr.max(axis = 0))

arr = arr + 5
print(arr)

[20. 50. 80.]
[70 80 90]
[[15 25 35]
 [45 55 65]
 [75 85 95]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(arr[arr % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20]


In [10]:
import pandas as pd
df = pd.read_csv("../datasets/Iris.csv")

arr = df.to_numpy()

print(arr.shape)
print(arr.size)
print(arr.ndim)

(150, 6)
900
2
